### ISSUE TITLE
Callback URL confusing

### ISSUE THREAD

**Issue by tjaensch** [auth0-blog/auth0-golang-jwt#1]
Under Setup it says "Add localhost:3000 to your Allowed Callback URL's in your Auth0 Management Dashboard." but in the .env file it's set to "AUTH0_CALLBACK_URL=http://localhost:3000/callback"?

**Comment by kukicado** [comment]
You can set it to either localhost:3000 or localhost:3000/callback. In our scenario setting it to just localhost:3000 would be fine but in a real world application you would want to have a separation of concerns where at the /callback route you would perform some additional operations. Does that make sense?
