### ISSUE TITLE
jwt.Claims does not support indexing

### ISSUE THREAD

**Issue by Linicks** [auth0-blog/auth0-golang-jwt#2]
All,
  I'm getting the following error when I try this example:

go run main.go                                                                          
# command-line-arguments

./main.go:65: invalid operation: token.Claims["admin"](type jwt.Claims does not support indexing)  
./main.go:66: invalid operation: token.Claims["name"](type jwt.Claims does not support indexing)  
./main.go:67: invalid operation: token.Claims["exp"](type jwt.Claims does not support indexing)   

Currently using Golang 1.7, Ubuntu 16.04x64

Thanks!
--Nick

**Comment by srt32** [comment]
@Linicks, this issue should be resolved by https://github.com/auth0-blog/auth0-golang-jwt/pull/3

**Comment by Linicks** [comment]
@srt32 :  Awesome! That fixed that issue, hopefully they will get #3 committed ASAP.

**Comment by kukicado** [comment]
As @srt32 said and fixed. A new version of the library changed how claims are made. Thanks @srt32. The fix has been merged.
